# Generated by Django 4.0.3 on 2022-05-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0005_payment_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='elevy',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_charge',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
