# Generated by Django 4.0.3 on 2022-05-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0006_payment_elevy_payment_payment_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='elevy',
            field=models.PositiveIntegerField(),
        ),
    ]
