# Generated by Django 4.0.3 on 2022-05-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0008_remove_payment_elevy_remove_payment_payment_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='elevy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_charge',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
