# Generated by Django 4.0.3 on 2022-05-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0009_payment_elevy_payment_payment_charge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='elevy',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_charge',
        ),
    ]
