# Generated by Django 4.0.3 on 2022-05-23 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0011_paymentfees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentfees',
            old_name='Delivery_fee',
            new_name='Delivery_area',
        ),
    ]
