# Generated by Django 4.0.3 on 2022-05-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0012_rename_delivery_fee_paymentfees_delivery_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentfees',
            options={'verbose_name': 'PaymentFee', 'verbose_name_plural': 'PaymentFees'},
        ),
    ]
