# Generated by Django 4.0.3 on 2022-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0013_alter_paymentfees_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentfees',
            name='Delivery_fee',
            field=models.CharField(choices=[('Accra', '20'), ('Kasoa', '30'), ('Tema', '20'), ('Kumasi', '100')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentfees',
            name='Delivery_area',
            field=models.CharField(choices=[('Accra', 'Accra'), ('Kasoa', 'Kasoa'), ('Tema', 'Tema'), ('Kumasi', 'Kumasi'), ('Eastern', 'Eastern')], max_length=200),
        ),
    ]
