# Generated by Django 4.0.3 on 2022-03-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
