# Generated by Django 4.0.3 on 2022-04-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0002_alter_tsu_mi_details_options_tsu_mi_details_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_title', models.CharField(max_length=100)),
                ('card_price', models.CharField(max_length=100)),
                ('card_img', models.URLField(max_length=200000)),
            ],
        ),
    ]
