# Generated by Django 4.0.3 on 2022-03-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0002_alter_userinformations_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinformations',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
