# Generated by Django 4.0.3 on 2022-03-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0003_rename_phone_number_userinformations_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformations',
            name='gender',
        ),
    ]
