# Generated by Django 4.0.3 on 2022-03-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0004_remove_userinformations_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='gender',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
