# Generated by Django 4.0.3 on 2022-05-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0004_payment_alter_popular_details_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='fullname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
