# Generated by Django 4.0.3 on 2022-03-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0005_userinformations_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm_pass', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Register_Account',
                'verbose_name_plural': 'Register_Accounts',
            },
        ),
    ]
