# Generated by Django 4.0.3 on 2022-05-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0010_remove_payment_elevy_remove_payment_payment_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_charge', models.PositiveIntegerField()),
                ('elevy', models.PositiveIntegerField()),
                ('Delivery_fee', models.CharField(choices=[('XXXXX', 'Accra'), ('XXXX', 'Kasoa'), ('XXX', 'Tema'), ('XX', 'Kumasi'), ('X', 'Eastern')], max_length=200)),
            ],
        ),
    ]
