# Generated by Django 4.0.3 on 2022-05-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsumitheapp', '0015_rename_payment_charge_paymentfees_paystack_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentfees',
            name='Delivery_fee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='paymentfees',
            name='elevy',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='paymentfees',
            name='paystack_fee',
            field=models.IntegerField(),
        ),
    ]
